export const languages: { code: string; name: string }[] = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'pt', name: 'Português' },
  { code: 'ar', name: 'العربية' },
  { code: 'ja', name: '日本語' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'de', name: 'Deutsch' },
  { code: 'fr', name: 'Français' },
  { code: 'ru', name: 'Русский' },
  { code: 'id', name: 'Indonesia' },
  { code: 'pl', name: 'Polski' },
  { code: 'it', name: 'Italiano' },
  { code: 'ko', name: '한국어' },
  { code: 'zh', name: '中文' },
  { code: 'ta', name: 'தமிழ்' },
  { code: 'ro', name: 'Română' },
  { code: 'th', name: 'ไทย' },
  { code: 'ur', name: 'اردو' },
  { code: 'he', name: 'עברית' },
  { code: 'te', name: 'తెలుగు' },
  { code: 'ml', name: 'മലയാളം' },
  { code: 'az', name: 'Azərbaycan' },
  { code: 'nl', name: 'Nederlands' },
  { code: 'hu', name: 'Magyar' },
  { code: 'vi', name: 'Tiếng Việt' },
  { code: 'bn', name: 'বাংলা' },
  { code: 'uk', name: 'Українська' },
  { code: 'fa', name: 'فارسی' },
  { code: 'el', name: 'Ελληνικά' },
  { code: 'ka', name: 'ქართული' },
  { code: 'bg', name: 'Български' },
  { code: 'hr', name: 'Hrvatski' },
  { code: 'sr', name: 'Српски' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'gu', name: 'ગુજરાતી' },
  { code: 'uz', name: 'O‘zbek' },
  { code: 'lt', name: 'Lietuvių' },
];

export const btnLanguages: { code: string; name: string }[] = [
  { code: 'English', name: 'English' },
  { code: 'Deutsch', name: 'Deutsch' },
  { code: 'Español', name: 'Español' },
  { code: 'Français', name: 'Français' },
  { code: 'Bahasa Indonesia', name: 'Bahasa Indonesia' },
  { code: 'Italiano', name: 'Italiano' },
  { code: '日本語', name: '日本語' },
  { code: '한국어', name: '한국어' },
  { code: 'Nederlands', name: 'Nederlands' },
  { code: 'Polski', name: 'Polski' },
  { code: 'Português', name: 'Português' },
  { code: 'Română', name: 'Română' },
  { code: 'Русский', name: 'Русский' },
  { code: 'ภาษาไทย', name: 'ภาษาไทย' },
  { code: 'Türkçe', name: 'Türkçe' },
  { code: 'Tiếng Việt', name: 'Tiếng Việt' },
  { code: '中文(简体)', name: '中文(简体)' },
  { code: '中文(繁體)', name: '中文(繁體)' },
];
