interface MenuItemProps {
  title: string; // Main category title
  subcategories?: Subcategory[]; // Optional subcategories
}

interface Subcategory {
  title?: string; // Title of the subcategory
  name?: string; // Alternative to `title` in some cases
  group?: string; // Used for grouped subcategories like "Popular Issuers"
  items?: Subcategory[]; // Nested subcategories for groups
  subcategories?: string[] | Subcategory[]; // Array of strings or nested Subcategory objects
  topics?: string[]; // Array of topics (used in specific subcategories)
}

export const menuItems: MenuItemProps[] = [
  {
    title: "Certification Preparation",
    subcategories: [
      {
        title: "Popular Issuers",
        items: [
          {
            title: "Amazon Web Services (AWS) Certifications",
            subcategories: [
              { title: "AWS Certified Solutions Architect - Associate" },
              { title: "AWS Certified Cloud Practitioner" },
              { title: "AWS Certified Developer - Associate" },
              { title: "AWS Certified SysOps Administrator - Associate" },
              { title: "AWS Certified Solutions Architect - Professional" },
              { title: "AWS Certified DevOps Engineer - Professional" },
              { title: "AWS Certified Security - Specialty" },
              { title: "AWS Certified Machine Learning - Specialty" },
              { title: "AWS Certified Advanced Networking - Specialty" },
            ],
          },
          {
            title: "Microsoft Certifications",
            subcategories: [
              { title: "AZ-900: Microsoft Azure Fundamentals" },
              { title: "AZ-104: Microsoft Azure Administrator Associate" },
              { title: "AZ-204: Microsoft Azure Developer Associate" },
              { title: "PL-300: Microsoft Power BI Data Analyst Associate" },
              { title: "PL-900: Microsoft Power Platform Fundamentals" },
              { title: "AI-900: Microsoft Azure AI Fundamentals" },
              { title: "AZ-500: Microsoft Azure Security Engineer Associate" },
              { title: "DP-900: Microsoft Azure Data Fundamentals" },
              { title: "DP-203: Microsoft Azure Data Engineer Associate" },
              { title: "AZ-400: Microsoft DevOps Engineer Expert" },
              { title: "AZ-305: Microsoft Azure Solutions Architect Expert" },
              { title: "MS-900: Microsoft 365 Fundamentals" },
              {
                title: "SC-200: Microsoft Security Operations Analyst Associate",
              },
              {
                title: "SC-900: Microsoft Security, Compliance, and Identity Fundamentals",
              },
              { title: "DP-100: Microsoft Azure Data Scientist Associate" },
            ],
          },
          {
            title: "Cisco Certifications",
            subcategories: [
              { title: "Cisco Certified Network Associate (CCNA)" },
              { title: "Cisco CCNP Enterprise" },
              { title: "Cisco Certified CyberOps Associate" },
              { title: "Cisco CCIE Security" },
              { title: "Cisco CCIE Enterprise Infrastructure" },
              { title: "Cisco CCNP Service Provider" },
              { title: "Cisco CCT Routing and Switching" },
              { title: "Cisco CCIE Data Center" },
            ],
          },
          {
            title: "CompTIA Certifications",
            subcategories: [
              { title: "CompTIA A+" },
              { title: "CompTIA Security+" },
              { title: "CompTIA Network+" },
              { title: "CompTIA Cybersecurity Analyst (CySA+)" },
              { title: "CompTIA Linux+" },
              { title: "CompTIA IT Fundamentals (ITF+)" },
              { title: "CompTIA PenTest+" },
              { title: "CompTIA Advanced Security Practitioner (CASP+)" },
              { title: "CompTIA Cloud+" },
              { title: "CompTIA Server+" },
              { title: "CompTIA Cloud Essentials+" },
              { title: "CompTIA Data+" },
            ],
          },
          {
            title: "Project Management Institute (PMI) Certifications",
            subcategories: [
              { title: "PMI Project Management Professional (PMP)" },
              { title: "PMI Certified Associate in Project Management (CAPM)" },
              { title: "PMI Agile Certified Practitioner (PMI-ACP)" },
              { title: "PMI Risk Management Professional (PMI-RMP)" },
              { title: "PMI Program Management Professional (PgMP)" },
              { title: "PMI Professional in Business Analysis (PMI-PBA)" },
              {
                title: "SAP Certified Associate - SAP Activate Project Manager",
              },
            ],
          },
          {
            title: "Google Cloud Certifications",
            subcategories: [
              { title: "Google Cloud Associate Cloud Engineer" },
              { title: "Google Cloud Professional Cloud Architect" },
              { title: "Google Cloud Professional Data Engineer" },
              { title: "Google Cloud Professional Cloud Developer" },
              { title: "Google Cloud Digital Leader" },
              { title: "Google Cloud Professional Cloud DevOps Engineer" },
              { title: "Google Cloud Professional Cloud Network Engineer" },
              { title: "Google Cloud Professional Cloud Security Engineer" },
              { title: "Google Cloud Professional Machine Learning Engineer" },
              { title: "Google Cloud Professional Cloud Database Engineer" },
            ],
          },
          {
            title: "Six Sigma Certifications",
            subcategories: [
              { title: "Lean Six Sigma Green Belt Certification" },
              { title: "Lean Six Sigma White Belt Certification" },
              { title: "Lean Six Sigma Yellow Belt Certification" },
              { title: "Lean Six Sigma Black Belt Certification" },
              { title: "Six Sigma Black Belt Certification" },
              { title: "Six Sigma Green Belt Certification" },
              { title: "Six Sigma Yellow Belt Certification" },
              { title: "Six Sigma White Belt Certification" },
            ],
          },
          {
            title: "Oracle Certifications",
            subcategories: [
              { title: "1Z0-071: Oracle Database SQL Certified Associate" },
              {
                title: "1Z0-808: Oracle Certified Associate, Java SE 8 Programmer",
              },
              {
                title: "1Z0-819: Oracle Certified Professional: Java SE 11 Developer",
              },
              {
                title: "1Z0-149: Oracle Database PL/SQL Developer Certified Professional",
              },
              {
                title: "1Z0-133: Oracle Certified Associate, WebLogic Server 12c Administrator",
              },
            ],
          },
        ],
      },

      {
        title: "Popular Subjects",
        items: [
          {
            title: "Cloud Certification",
            subcategories: [
              { title: "AWS Certified Solutions Architect - Associate" },
              { title: "AWS Certified Cloud Practitioner" },
              { title: "AZ-900: Microsoft Azure Fundamentals" },
              { title: "AWS Certified Developer - Associate" },
              { title: "AZ-104: Microsoft Azure Administrator Associate" },
              { title: "AWS Certified SysOps Administrator - Associate" },
              { title: "AWS Certified Solutions Architect - Professional" },
              { title: "Google Cloud Associate Cloud Engineer" },
              { title: "Google Cloud Professional Cloud Architect" },
              { title: "Certified Kubernetes Administrator (CKA)" },
              { title: "AWS Certified DevOps Engineer - Professional" },
              { title: "AWS Certified Security - Specialty" },
              { title: "AZ-204: Microsoft Azure Developer Associate" },
              { title: "Google Cloud Professional Data Engineer" },
              { title: "AWS Certified Machine Learning - Specialty" },
            ],
          },
          {
            title: "Networking Certification",
            subcategories: [
              { title: "Cisco Certified Network Associate (CCNA)" },
              { title: "CompTIA Network+" },
              { title: "Cisco CCNP Enterprise" },
              { title: "AWS Certified Advanced Networking - Specialty" },
              {
                title: "Juniper Networks Certified Internet Associate (JNCIA)",
              },
              { title: "F5 BIG-IP Certification" },
              {
                title: "VMware Certified Professional - Network Virtualization (VCP-NV)",
              },
              { title: "Cisco CCIE Enterprise Infrastructure" },
              {
                title: "Juniper Networks Certified Internet Specialist (JNCIS)",
              },
              { title: "Cisco CCNP Service Provider" },
              { title: "Cisco CCT Routing and Switching" },
              {
                title: "Palo Alto Networks Certified Network Security Administrator (PCNSA)",
              },
              { title: "HashiCorp Certified: Consul Associate" },
            ],
          },
          {
            title: "Cybersecurity Certification",
            subcategories: [
              { title: "CompTIA Security+" },
              {
                title: "Certified Information Systems Security Professional (CISSP)",
              },
              { title: "AWS Certified Security - Specialty" },
              { title: "CompTIA Cybersecurity Analyst (CySA+)" },
              { title: "Certified in Cybersecurity (CC)" },
              { title: "Certified Information Security Manager (CISM)" },
              { title: "CompTIA PenTest+" },
              { title: "Certified Information Systems Auditor (CISA)" },
              { title: "Cisco Certified CyberOps Associate" },
              { title: "CompTIA Advanced Security Practitioner (CASP+)" },
              { title: "Certified Cloud Security Professional (CCSP)" },
              {
                title: "Certified in Risk and Information Systems Control (CRISC)",
              },
              {
                title: "SC-200: Microsoft Security Operations Analyst Associate",
              },
              { title: "Google Cloud Professional Cloud Security Engineer" },
              {
                title: "SC-900: Microsoft Security, Compliance, and Identity Fundamentals",
              },
            ],
          },
          {
            title: "Project Management Certification",
            subcategories: [
              { title: "PMI Project Management Professional (PMP)" },
              { title: "PMI Certified Associate in Project Management (CAPM)" },
              { title: "PMI Agile Certified Practitioner (PMI-ACP)" },
              { title: "PMI Risk Management Professional (PMI-RMP)" },
              { title: "PMI Program Management Professional (PgMP)" },
              { title: "PMI Professional in Business Analysis (PMI-PBA)" },
              {
                title: "SAP Certified Associate - SAP Activate Project Manager",
              },
            ],
          },
          {
            title: "DevOps Certification",
            subcategories: [
              { title: "CompTIA A+" },
              { title: "CompTIA IT Fundamentals (ITF+)" },
              { title: "Japanese Information Technology Passport Examination" },
              { title: "COBIT Foundation Certificate" },
            ],
          },
          {
            title: "Coding Certification",
            subcategories: [
              { title: "AWS Certified Developer - Associate" },
              { title: "Certified Entry-Level Python Programmer (PCEP)" },
              { title: "Certified Associate in Python Programming (PCAP)" },
              {
                title: "1Z0-819: Oracle Certified Professional: Java SE 11 Developer",
              },
            ],
          },
          {
            title: "System Administration Certification",
            subcategories: [
              { title: "Red Hat Certified System Administrator (RHCSA)" },
              { title: "Red Hat Certified Engineer (RHCE)" },
              {
                title: "VMware Certified Professional - Desktop Management (VCP-DTM)",
              },
              { title: "MS-700: Microsoft 365 Teams Administrator Associate" },
              {
                title: "MS-203: Microsoft 365 Messaging Administrator Associate",
              },
              {
                title: "1Z0-133: Oracle Certified Associate, WebLogic Server 12c Administrator",
              },
            ],
          },
          {
            title: "Artificial Intelligence Certification",
            subcategories: [
              { title: "AWS Certified Machine Learning - Specialty" },
              { title: "AI-900: Microsoft Azure AI Fundamentals" },
              { title: "DP-100: Microsoft Azure Data Scientist Associate" },
              { title: "Google Cloud Professional Machine Learning Engineer" },
              { title: "AI-102: Microsoft Azure AI Engineer Associate" },
              { title: "Databricks Certified Data Engineer Associate" },
              { title: "Splunk Enterprise Certified Admin" },
              {
                title: "Databricks Certified Associate Developer for Apache Spark",
              },
              { title: "Splunk Core Certified Power User" },
              { title: "Splunk Core Certified User" },
            ],
          },
        ],
      },
    ],
  },

  {
    title: "Development",
    subcategories: [
      {
        title: "Web Development",
        subcategories: [
          { title: "JavaScript" },
          { title: "React JS" },
          { title: "Angular" },
          { title: "Next.js" },
          { title: "CSS" },
          { title: "Node.Js" },
          { title: "HTML" },
          { title: "Typescript" },
        ],
      },
      {
        title: "Data Science",
        subcategories: [
          { title: "Machine Learning" },
          { title: "Artificial Intelligence (AI)" },
          { title: "Python" },
          { title: "Large Language Models (LLM)" },
          { title: "Deep Learning" },
          { title: "Generative AI (GenAI)" },
          { title: "MLOps" },
          { title: "Data Analysis" },
        ],
      },
      {
        title: "Mobile Development",
        subcategories: [
          { title: "Google Flutter" },
          { title: "iOS Development" },
          { title: "React Native" },
          { title: "Android Development" },
          { title: "Dart (programming language)" },
          { title: "Swift" },
          { title: "SwiftUI" },
          { title: "Kotlin" },
          { title: "Mobile App Development" },
        ],
      },
      {
        title: "Programming Languages",
        subcategories: [
          { title: "Python" },
          { title: "Java" },
          { title: "C# (programming language)" },
          { title: "C++ (programming language)" },
          { title: "React JS" },
          { title: "C (programming language)" },
          { title: "Go (programming language)" },
          { title: "Spring Framework" },
          { title: "Rust (programming language)" },
        ],
      },
      {
        title: "Game Development",
        subcategories: [
          { title: "Unreal Engine" },
          { title: "Unity" },
          { title: "Game Development Fundamentals" },
          { title: "3D Game Development" },
          { title: "C# (programming language)" },
          { title: "Unreal Engine Blueprints" },
          { title: "Godot" },
          { title: "2D Game Development" },
          { title: "C++ (programming language)" },
        ],
      },
      {
        title: "Database Design & Development",
        subcategories: [
          { title: "SQL" },
          { title: "MySQL" },
          { title: "Database Management Systems (DBMS)" },
          { title: "SQL Server" },
          { title: "PostgreSQL" },
          { title: "MongoDB" },
          { title: "Oracle SQL" },
          { title: "Apache Kafka" },
          { title: "Database Administration" },
        ],
      },
      {
        title: "Software Testing",
        subcategories: [
          { title: "Microsoft Playwright" },
          { title: "Selenium WebDriver" },
          { title: "Java" },
          { title: "Automation Testing" },
          { title: "ISTQB Certified Tester Foundation Level (CTFL)" },
          { title: "Postman" },
          { title: "Selenium Testing Framework" },
          { title: "API Testing" },
        ],
      },
      {
        title: "Software Engineering",
        subcategories: [
          { title: "Data Structures" },
          { title: "Software Architecture" },
          { title: "Certified Kubernetes Application Developer (CKAD)" },
          { title: "Algorithms" },
          { title: "Coding Interview" },
          { title: "Spring Framework" },
          { title: "Microservices" },
          { title: "Back End Web Development" },
          { title: "Software Practices" },
        ],
      },
      {
        title: "Software Development Tools",
        subcategories: [
          { title: "Docker" },
          { title: "Git" },
          { title: "Kubernetes" },
          { title: "Prompt Engineering" },
          { title: "GitHub Copilot" },
          { title: "GitHub" },
          { title: "JIRA" },
          { title: "Confluence" },
          { title: "CI/CD" },
        ],
      },
      {
        title: "No-Code Development",
        subcategories: [
          { title: "Generative AI (GenAI)" },
          { title: "WordPress" },
          { title: "Microsoft Power Apps" },
          { title: "Microsoft Power Automate" },
          { title: "Microsoft Power Platform" },
          { title: "Bubble Visual Programming" },
          { title: "Web Design" },
          { title: "Microsoft Copilot" },
          { title: "Dify" },
        ],
      },
    ],
  },

  {
    title: "Business",
    subcategories: [
      {
        title: "Entrepreneurship",
        subcategories: [
          { title: "Business Fundamentals" },
          { title: "Entrepreneurship Fundamentals" },
          { title: "Online Business" },
          { title: "Business Strategy" },
          { title: "ChatGPT" },
          { title: "Startup" },
          { title: "Freelancing" },
          { title: "Business Plan" },
          { title: "QuickBooks" },
        ],
      },
      {
        title: "Communication",
        subcategories: [
          { title: "Communication Skills" },
          { title: "Presentation Skills" },
          { title: "Public Speaking" },
          { title: "Writing" },
          { title: "Fiction Writing" },
          { title: "Business Communication" },
          { title: "Storytelling" },
          { title: "Assertiveness" },
          { title: "Business Writing" },
        ],
      },
      {
        title: "Management",
        subcategories: [
          { title: "Product Management" },
          { title: "Leadership" },
          { title: "Management Skills" },
          { title: "Business Strategy" },
          { title: "ISO 9001" },
          { title: "Business Fundamentals" },
          { title: "Project Management" },
          { title: "Quality Management" },
          { title: "Risk Management" },
        ],
      },
      {
        title: "Sales",
        subcategories: [
          { title: "Sales Skills" },
          { title: "B2B Sales" },
          { title: "LinkedIn" },
          { title: "Customer Service" },
          { title: "Sales Management" },
          { title: "Cold Calling" },
          { title: "Customer Success Management (CSM)" },
          { title: "Business Development" },
          { title: "Persuasion" },
        ],
      },
      {
        title: "Business Strategy",
        subcategories: [
          { title: "Artificial Intelligence (AI)" },
          { title: "Environmental, Social and Governance (ESG)" },
          { title: "ChatGPT" },
          { title: "Management Consulting" },
          { title: "IIBA Entry Certificate in Business Analysis (ECBA)" },
          { title: "Prompt Engineering" },
          { title: "Custom GPTs / GPT Builder" },
          {
            title: "The Open Group Certified: TOGAF Enterprise Architecture Foundation",
          },
        ],
      },
      {
        title: "Operations",
        subcategories: [
          { title: "Supply Chain" },
          { title: "Lean Six Sigma Green Belt Certification" },
          { title: "Logistics Management" },
          { title: "Lean Six Sigma Black Belt Certification" },
          { title: "Operations Management" },
          { title: "Virtual Assistant Skills" },
          { title: "Lean" },
          { title: "Quality Management" },
          { title: "Inventory Management" },
        ],
      },
      {
        title: "Project Management",
        subcategories: [
          { title: "PMI Project Management Professional (PMP)" },
          { title: "PMI Certified Associate in Project Management (CAPM)" },
          { title: "PMI PMBOK" },
          { title: "Agile" },
          { title: "Scrum" },
          { title: "Professional Scrum Master (PSM)" },
          { title: "PRINCE2" },
          { title: "PMI Agile Certified Practitioner (PMI-ACP)" },
        ],
      },
      {
        title: "Business Law",
        subcategories: [
          { title: "Law" },
          { title: "Certified Information Privacy Professional (CIPP)" },
          { title: "Contract Management" },
          { title: "Compliance Management" },
          { title: "GDPR" },
          { title: "Contract Law" },
          { title: "Legal English" },
          { title: "Healthcare IT" },
        ],
      },
      {
        title: "Business Analytics & Intelligence",
        subcategories: [
          { title: "Microsoft Power BI" },
          { title: "SQL" },
          { title: "Data Modeling" },
          { title: "Data Analysis" },
          { title: "Business Analysis" },
          { title: "Tableau" },
          { title: "Business Intelligence (BI)" },
          { title: "Data Analysis Expressions (DAX)" },
          { title: "Business Analytics" },
        ],
      },
      {
        title: "Human Resources",
        subcategories: [
          { title: "Recruiting and Hiring" },
          { title: "HR Analytics" },
          { title: "Professional in Human Resources (PHR)" },
          { title: "Employment Law" },
          { title: "Corporate Learning and Development (L&D)" },
          {
            title: "Society for Human Resource Management Certified Professional (SHRM-CP)",
          },
          { title: "Payroll Accounting" },
          { title: "Emotional Intelligence" },
        ],
      },
      {
        title: "Industry",
        subcategories: [
          { title: "Piping" },
          { title: "Oil and Gas Industry" },
          { title: "Chemical Engineering" },
          { title: "Aviation" },
          { title: "Control Engineering" },
          { title: "Workplace Health and Safety" },
          { title: "Medical Device Development" },
          { title: "Electrical Engineering" },
          { title: "Lean Manufacturing" },
        ],
      },
      {
        title: "E-Commerce",
        subcategories: [
          { title: "Dropshipping" },
          { title: "Amazon FBA" },
          { title: "Shopify Dropshipping" },
          { title: "Shopify" },
          { title: "Etsy" },
          { title: "Amazon Kindle Direct Publishing (KDP)" },
          { title: "Online Business" },
          { title: "Selling on Amazon" },
        ],
      },
      {
        title: "Media",
        subcategories: [
          { title: "Content Creation" },
          { title: "Audiobook Creation" },
          { title: "Creative Writing" },
          { title: "Amazon Kindle Direct Publishing (KDP)" },
          { title: "Screenwriting and Scriptwriting" },
          { title: "Scrivener" },
          { title: "Search Engine Optimization (SEO)" },
          { title: "YouTube Marketing" },
          { title: "Generative AI (GenAI)" },
        ],
      },
      {
        title: "Real Estate",
        subcategories: [
          { title: "Real Estate Investing" },
          { title: "Construction" },
          { title: "Airbnb Hosting" },
          { title: "Financial Modeling" },
          { title: "Mortgage" },
          { title: "Real Estate Flipping" },
          { title: "Property Management" },
          { title: "Real Estate Marketing" },
        ],
      },
      {
        title: "Other Business",
        subcategories: [
          { title: "ChatGPT" },
          { title: "QuickBooks" },
          { title: "Data Entry Skills" },
          { title: "Grant Writing" },
          { title: "Artificial Intelligence (AI)" },
          { title: "Generative AI (GenAI)" },
          { title: "Reiki" },
          { title: "Transcription" },
          { title: "Freelance Writing" },
        ],
      },
    ],
  },

  {
    title: "Finance & Accounting",
    subcategories: [
      {
        title: "Accounting & Bookkeeping",
        subcategories: [
          { title: "Accounting" },
          { title: "Bookkeeping" },
          { title: "QuickBooks" },
          { title: "Financial Accounting" },
          { title: "Finance Fundamentals" },
          { title: "TallyPrime (Tally.ERP)" },
          { title: "Uniform CPA Examination" },
          { title: "International Financial Reporting Standards (IFRS)" },
          { title: "Financial Statement" },
        ],
      },
      {
        title: "Compliance",
        subcategories: [
          { title: "Anti-Money Laundering (AML)" },
          { title: "Criminology" },
          { title: "Internal Controls" },
          { title: "Compliance Management" },
          { title: "Fraud Analytics" },
          { title: "Risk Management" },
          { title: "Sarbanes-Oxley (SOX)" },
          { title: "Trade and Commerce" },
          { title: "Internal Auditing" },
        ],
      },
      {
        title: "Cryptocurrency & Blockchain",
        subcategories: [
          { title: "Cryptocurrency" },
          { title: "Bitcoin" },
          { title: "Blockchain" },
          { title: "Binance" },
          { title: "Day Trading" },
          { title: "Algorithmic Trading" },
          { title: "Bitcoin Trading" },
          { title: "Cryptography" },
          { title: "NFT (Non-Fungible Tokens)" },
        ],
      },
      {
        title: "Economics",
        subcategories: [
          { title: "Macroeconomics" },
          { title: "Microeconomics" },
          { title: "Global Economics" },
          { title: "Finance Fundamentals" },
          { title: "Stata" },
          { title: "Behavioral Economics" },
          { title: "Econometrics" },
          { title: "Personal Finance" },
        ],
      },
      {
        title: "Finance",
        subcategories: [
          { title: "Personal Finance" },
          { title: "Investment Banking" },
          { title: "Finance Fundamentals" },
          { title: "Banking" },
          { title: "Corporate Finance" },
          { title: "Chartered Financial Analyst (CFA)" },
          { title: "Financial Analysis" },
          { title: "Financial Management" },
          { title: "ChatGPT" },
        ],
      },
      {
        title: "Finance Cert & Exam Prep",
        subcategories: [
          { title: "Chartered Financial Analyst (CFA)" },
          { title: "Certified Internal Auditor (CIA)" },
          { title: "Certified Management Accountant (CMA)" },
          { title: "Association of Chartered Certified Accountants (ACCA)" },
          { title: "ANBIMA Certification" },
          { title: "Certified Financial Planner (CFP)" },
          { title: "Cost Accounting" },
          { title: "FINRA Securities Industry Essentials (SIE)" },
          { title: "Risk Management" },
        ],
      },
      {
        title: "Financial Modeling & Analysis",
        subcategories: [
          { title: "Financial Analysis" },
          { title: "Financial Modeling" },
          { title: "Microsoft Excel" },
          { title: "Investment Banking" },
          { title: "Accounting" },
          { title: "Finance Fundamentals" },
          { title: "Financial Planning" },
          { title: "Python" },
          { title: "Business Budgeting" },
        ],
      },
      {
        title: "Investing & Trading",
        subcategories: [
          { title: "Stock Trading" },
          { title: "Investing" },
          { title: "Technical Analysis (finance)" },
          { title: "Forex Trading" },
          { title: "Financial Markets" },
          { title: "Algorithmic Trading" },
          { title: "Day Trading" },
          { title: "Options Trading" },
          { title: "Financial Trading" },
        ],
      },
      {
        title: "Money Management Tools",
        subcategories: [
          { title: "QuickBooks" },
          { title: "SAP FICO" },
          { title: "Xero" },
          { title: "Microsoft Excel" },
          { title: "Personal Finance" },
          { title: "Excel Analytics" },
          { title: "Financial Modeling" },
          { title: "Credit Repair" },
          { title: "Financial Analysis" },
        ],
      },
      {
        title: "Taxes",
        subcategories: [
          { title: "Tax Preparation" },
          { title: "Goods and Services Tax (GST)" },
          { title: "Accounting" },
          { title: "Value Added Tax (VAT)" },
          { title: "Transfer Pricing" },
          { title: "Finance Fundamentals" },
          { title: "Control Systems" },
          { title: "Home Business" },
        ],
      },
      {
        title: "Other Finance & Accounting",
        subcategories: [
          { title: "Budgeting" },
          { title: "Expense Management" },
          { title: "Audit Preparation" },
          { title: "Financial Technology (FinTech)" },
          { title: "Cash Flow Management" },
          { title: "Debt Management" },
          { title: "Wealth Management" },
        ],
      },
    ],
  },

  {
    title: "IT & Software",
    subcategories: [
      {
        title: "IT Certifications",
        subcategories: [
          { title: "AWS Certified Cloud Practitioner" },
          { title: "AWS Certified Solutions Architect - Associate" },
          { title: "CompTIA Security+" },
          { title: "CompTIA A+" },
          { title: "Amazon AWS" },
          { title: "Cisco Certified Network Associate (CCNA)" },
          { title: "CompTIA Network+" },
          { title: "Information Security" },
          { title: "AWS Certified AI Practitioner" },
        ],
      },
      {
        title: "Network & Security",
        subcategories: [
          { title: "Ethical Hacking" },
          { title: "Cybersecurity" },
          { title: "Network Security" },
          { title: "IT Networking Fundamentals" },
          { title: "Penetration Testing" },
          { title: "Kubernetes" },
          { title: "CompTIA Security+" },
          { title: "IT Auditing" },
          { title: "Certified Information Systems Auditor (CISA)" },
        ],
      },
      {
        title: "Hardware",
        subcategories: [
          { title: "PLC" },
          { title: "Arduino" },
          { title: "Electronics" },
          { title: "Embedded Systems" },
          { title: "Microcontroller" },
          { title: "Raspberry Pi" },
          { title: "Embedded C" },
          { title: "HMI" },
          { title: "Robotic Process Automation (RPA)" },
        ],
      },
      {
        title: "Operating Systems & Servers",
        subcategories: [
          { title: "Linux" },
          { title: "Linux Administration" },
          { title: "Windows Server" },
          { title: "PowerShell" },
          { title: "Active Directory" },
          { title: "Shell Scripting" },
          { title: "Proxmox VE" },
          { title: "Linux Command Line" },
          { title: "Operating System" },
        ],
      },
      {
        title: "Other IT & Software",
        subcategories: [
          { title: "ChatGPT" },
          { title: "DevOps" },
          { title: "Python" },
          { title: "Generative AI (GenAI)" },
          { title: "Data Science" },
          { title: "Microsoft Excel" },
          { title: "Terraform" },
          { title: "Kubernetes" },
          { title: "C# (programming language)" },
        ],
      },
    ],
  },

  {
    title: "Office Productivity",
    subcategories: [
      {
        title: "Microsoft",
        subcategories: [
          { title: "Microsoft Excel" },
          { title: "Microsoft 365 (Office)" },
          { title: "Microsoft Power BI" },
          { title: "Excel VBA" },
          { title: "PowerPoint" },
          { title: "Excel Formulas and Functions" },
          { title: "Pivot Tables" },
          { title: "Data Analysis" },
          { title: "Microsoft SharePoint" },
        ],
      },
      {
        title: "Apple",
        subcategories: [
          { title: "Mac Basics" },
          { title: "iMovie" },
          { title: "Apple Keynote" },
          { title: "Apple Products Basics" },
          { title: "Numbers For Mac" },
          { title: "macOS" },
          { title: "Mac Pages" },
          { title: "Personal Productivity" },
          { title: "Microsoft 365 (Office)" },
        ],
      },
      {
        title: "Google",
        subcategories: [
          { title: "Google Sheets" },
          { title: "Google Workspace (G Suite)" },
          { title: "Google Looker Studio (Data Studio)" },
          { title: "Google AppSheet" },
          { title: "Google Looker" },
          { title: "Google Apps Script" },
          { title: "Gmail Productivity" },
          { title: "Google Drive" },
          { title: "Microsoft Excel" },
        ],
      },
      {
        title: "SAP",
        subcategories: [
          { title: "SAP S/4HANA" },
          { title: "SAP Materials Management (SAP MM)" },
          { title: "SAP ABAP" },
          { title: "SAP Business Technology Platform (SAP BTP)" },
          { title: "SAP Sales and Distribution (SAP SD)" },
          { title: "SAP FICO" },
          { title: "SAP HCM" },
          { title: "SAP Analytics Cloud" },
        ],
      },
      {
        title: "Oracle",
        subcategories: [
          { title: "Oracle Primavera" },
          { title: "Oracle SQL" },
          { title: "Oracle Fusion HCM" },
          { title: "PL/SQL" },
          { title: "Oracle Database" },
          { title: "Database Administration" },
          { title: "Project Management" },
          { title: "Oracle ERP" },
          { title: "Oracle E-Business Suite" },
        ],
      },
      {
        title: "Other Office Productivity",
        subcategories: [
          { title: "ChatGPT" },
          { title: "Python" },
          { title: "Programming Fundamentals" },
          { title: "Generative AI (GenAI)" },
          { title: "Notion Workspace" },
          { title: "Prompt Engineering" },
          { title: "ServiceNow" },
          { title: "Automation" },
          { title: "Typing" },
        ],
      },
    ],
  },

  {
    title: "Personal Development",
    subcategories: [
      {
        title: "Personal Transformation",
        subcategories: [
          { title: "Life Coach Training" },
          { title: "Neuro-Linguistic Programming (NLP)" },
          { title: "Personal Development" },
          { title: "Sound Therapy" },
          { title: "Horsemanship" },
          { title: "Mindfulness" },
          { title: "Coaching" },
          { title: "Life Purpose" },
        ],
      },
      {
        title: "Personal Productivity",
        subcategories: [
          { title: "ChatGPT" },
          { title: "Time Management" },
          { title: "Notion Workspace" },
          { title: "Speed Reading" },
          { title: "Obsidian App" },
          { title: "Organizational Skills" },
          { title: "Writing" },
          { title: "Procrastination" },
          { title: "Focus Mastery" },
        ],
      },
      {
        title: "Memory and Study Skills",
        subcategories: [
          { title: "Memory" },
          { title: "Speed Reading" },
          { title: "Learning Strategies" },
          { title: "Study Skills" },
          { title: "Focus Mastery" },
          { title: "Mind Mapping" },
          { title: "Critical Thinking" },
          { title: "Artificial Intelligence (AI)" },
          { title: "Obsidian App" },
        ],
      },
      {
        title: "Motivation",
        subcategories: [
          { title: "Neuroplasticity" },
          { title: "English Grammar" },
          { title: "Neuro-Linguistic Programming (NLP)" },
          { title: "Coaching" },
          { title: "Manifestation and Law of Attraction" },
          { title: "Procrastination" },
          { title: "Personal Development" },
          { title: "Philosophy" },
        ],
      },
      {
        title: "Other Personal Management",
        subcategories: [
          { title: "Project Development" },
          { title: "Freight Brokering" },
          { title: "Public Speaking" },
          { title: "Personal Development" },
          { title: "Hypnotherapy" },
          { title: "Sound Therapy" },
          { title: "Lucid Dreaming" },
          { title: "Life Coach Training" },
          { title: "Car Repair" },
        ],
      },
      {
        title: "Leadership",
        subcategories: [
          { title: "Management Skills" },
          { title: "Manager Training" },
          { title: "Coaching" },
          { title: "Communication Skills" },
          { title: "Conflict Management" },
          { title: "Public Speaking" },
          { title: "Relationship Building" },
          { title: "Decision Making" },
        ],
      },
      {
        title: "Career Development",
        subcategories: [
          { title: "Interviewing Skills" },
          { title: "Job Search" },
          { title: "Resume and CV Writing" },
          { title: "Business Communication" },
          { title: "IT / Technical Support" },
          { title: "Business Writing" },
          { title: "Car Repair" },
          { title: "Building Inspection" },
        ],
      },
      {
        title: "Parenting & Relationships",
        subcategories: [
          { title: "Parenting" },
          { title: "Relationship Building" },
          { title: "Generative AI (GenAI)" },
          { title: "Couples Counseling" },
          { title: "Child Psychology" },
          { title: "Marriage" },
          { title: "Love" },
          { title: "Autism" },
          { title: "Dating" },
        ],
      },
      {
        title: "Happiness",
        subcategories: [
          { title: "Life Coach Training" },
          { title: "Manifestation and Law of Attraction" },
          { title: "Cognitive Behavioral Therapy (CBT)" },
          { title: "Neuro-Linguistic Programming (NLP)" },
          { title: "Positive Psychology" },
          { title: "Mindfulness" },
          { title: "Psychology" },
          { title: "Personal Success" },
        ],
      },
      {
        title: "Esoteric Practices",
        subcategories: [
          { title: "Reiki" },
          { title: "Energy Healing" },
          { title: "Tarot Reading" },
          { title: "Astrology" },
          { title: "Spiritual Healing" },
          { title: "Hypnotherapy" },
          { title: "Psychic" },
          { title: "Chakra" },
          { title: "Akashic Records" },
        ],
      },
      {
        title: "Religion & Spirituality",
        subcategories: [
          { title: "Spirituality" },
          { title: "Tarot Reading" },
          { title: "Energy Healing" },
          { title: "Life Coach Training" },
          { title: "Mindfulness" },
          { title: "Reiki" },
          { title: "Spiritual Healing" },
          { title: "The Bible" },
          { title: "Numerology" },
        ],
      },
      {
        title: "Personal Brand Building",
        subcategories: [
          { title: "Personal Branding" },
          { title: "Meetings" },
          { title: "LinkedIn" },
          { title: "Career Development" },
          { title: "Personal Networking" },
          { title: "Business Strategy" },
          { title: "Amazon Kindle Direct Publishing (KDP)" },
          { title: "Audiobook Creation" },
          { title: "Public Speaking" },
        ],
      },
      {
        title: "Creativity",
        subcategories: [
          { title: "Creative Writing" },
          { title: "Screenwriting and Scriptwriting" },
          { title: "Art Therapy" },
          { title: "Writing a Book" },
          { title: "Storytelling" },
          { title: "Writing" },
          { title: "Novel Writing" },
          { title: "Fiction Writing" },
          { title: "Self-Publishing" },
        ],
      },
      {
        title: "Influence",
        subcategories: [
          { title: "Voice Training" },
          { title: "Communication Skills" },
          { title: "Persuasion" },
          { title: "Negotiation" },
          { title: "Public Speaking" },
          { title: "Body Language" },
          { title: "English Grammar" },
          { title: "Presentation Skills" },
          { title: "Influence Skills" },
        ],
      },
      {
        title: "Self Esteem & Confidence",
        subcategories: [
          { title: "Confidence" },
          { title: "Self-Esteem" },
          { title: "Communication Skills" },
          { title: "Psychotherapy" },
          { title: "Personal Development" },
          { title: "Social Skills" },
          { title: "Family Constellations Therapy" },
          { title: "Public Speaking" },
          { title: "Dance" },
        ],
      },
      {
        title: "Stress Management",
        subcategories: [
          { title: "Anxiety Management" },
          { title: "Emotional Intelligence" },
          { title: "Resilience" },
          { title: "Coaching" },
          { title: "Anger Management" },
          { title: "Grief Healing" },
          { title: "Mindfulness" },
          { title: "Work Life Balance" },
        ],
      },
    ],
  },

  {
    title: "Design",
    subcategories: [
      {
        title: "Web Design",
        subcategories: [
          { title: "Mobile App Design" },
          { title: "WordPress" },
          { title: "CSS" },
          { title: "Figma" },
          { title: "User Interface Design" },
          { title: "Elementor" },
          { title: "Banner Design" },
          { title: "HTML" },
        ],
      },
      {
        title: "Graphic Design & Illustration",
        subcategories: [
          { title: "Graphic Design" },
          { title: "Canva" },
          { title: "Adobe Photoshop" },
          { title: "Drawing" },
          { title: "Adobe Illustrator" },
          { title: "Procreate Digital Illustration App" },
          { title: "Design Theory" },
          { title: "Digital Painting" },
          { title: "Adobe InDesign" },
        ],
      },
      {
        title: "Design Tools",
        subcategories: [
          { title: "AutoCAD" },
          { title: "Midjourney" },
          { title: "SOLIDWORKS" },
          { title: "Figma" },
          { title: "Adobe After Effects" },
          { title: "Procreate Digital Illustration App" },
          { title: "AI Art Generation" },
          { title: "Adobe Photoshop" },
          { title: "Canva" },
        ],
      },
      {
        title: "User Experience Design",
        subcategories: [
          { title: "User Experience (UX) Design" },
          { title: "Figma" },
          { title: "UX Writing (User Experience Writing)" },
          { title: "User Interface Design" },
          { title: "Generative AI (GenAI)" },
          { title: "Product Design" },
          { title: "Web Accessibility" },
          { title: "Design Thinking" },
          { title: "Adobe XD" },
        ],
      },
      {
        title: "Game Design",
        subcategories: [
          { title: "Pixel Art" },
          { title: "Unreal Engine" },
          { title: "Unity" },
          { title: "Blender" },
          { title: "VFX (Visual Effects)" },
          { title: "3D Environment Modeling" },
          { title: "Digital Painting" },
          { title: "3D Modeling" },
        ],
      },
      {
        title: "3D & Animation",
        subcategories: [
          { title: "Blender" },
          { title: "3D Modeling" },
          { title: "Adobe After Effects" },
          { title: "Autodesk Fusion" },
          { title: "Motion Graphics" },
          { title: "3D Printing" },
          { title: "3D Animation" },
          { title: "zBrush" },
          { title: "Unreal Engine" },
        ],
      },
      {
        title: "Fashion Design",
        subcategories: [
          { title: "Pattern Making (Fashion)" },
          { title: "Sewing" },
          { title: "Fashion" },
          { title: "3D Fashion Design" },
          { title: "Jewelry Design" },
          { title: "Jewelry Making" },
          { title: "Adobe Illustrator" },
          { title: "Textiles" },
        ],
      },
      {
        title: "Architectural Design",
        subcategories: [
          { title: "Revit" },
          { title: "AutoCAD" },
          { title: "Building Information Modeling (BIM)" },
          { title: "SketchUp" },
          { title: "LEED" },
          { title: "3D Modeling" },
          { title: "ARCHICAD" },
          { title: "Blender" },
        ],
      },
      {
        title: "Interior Design",
        subcategories: [
          { title: "SketchUp" },
          { title: "Color Theory" },
          { title: "Blender" },
          { title: "Lighting Design" },
          { title: "Home Staging" },
          { title: "Electrical Engineering" },
          { title: "Revit" },
          { title: "Electricity" },
        ],
      },
      {
        title: "Other Design",
        subcategories: [
          { title: "Electronics" },
          { title: "PCB Design" },
          { title: "Drawing" },
          { title: "Stable Diffusion" },
          { title: "Geometric Dimensioning and Tolerancing (GD&T)" },
          { title: "AutoCAD" },
          { title: "CATIA" },
          { title: "Microservices" },
          { title: "Software Architecture" },
        ],
      },
    ],
  },

  {
    title: "Marketing",
    subcategories: [
      {
        title: "Digital Marketing",
        subcategories: [
          { title: "Marketing Strategy" },
          { title: "Social Media Marketing" },
          { title: "Internet Marketing" },
          { title: "ChatGPT" },
          { title: "Google Analytics" },
          { title: "Copywriting" },
          { title: "Sales Funnel" },
          { title: "Startup" },
        ],
      },
      {
        title: "Search Engine Optimization",
        subcategories: [
          { title: "Search Engine Optimization (SEO)" },
          { title: "WordPress" },
          { title: "Keyword Research" },
          { title: "Google Business Profile (Google My Business)" },
          { title: "Local SEO" },
          { title: "SEO Audit" },
          { title: "Link Building" },
          { title: "ChatGPT" },
          { title: "SEMrush" },
        ],
      },
      {
        title: "Social Media Marketing",
        subcategories: [
          { title: "Instagram Marketing" },
          { title: "Social Media Management" },
          { title: "Facebook Ads" },
          { title: "Facebook Marketing" },
          { title: "TikTok Marketing" },
          { title: "YouTube Marketing" },
          { title: "Canva" },
          { title: "PPC Advertising" },
        ],
      },
      {
        title: "Branding",
        subcategories: [
          { title: "YouTube Audience Growth" },
          { title: "YouTube Marketing" },
          { title: "Business Branding" },
          { title: "Brand Management" },
          { title: "Personal Branding" },
          { title: "Marketing Strategy" },
          { title: "DaVinci Resolve" },
          { title: "Online Course Marketing" },
          { title: "Product Management" },
        ],
      },
      {
        title: "Marketing Fundamentals",
        subcategories: [
          { title: "Marketing Strategy" },
          { title: "Copywriting" },
          { title: "Marketing Psychology" },
          { title: "Digital Marketing" },
          { title: "Event Planning" },
          { title: "Marketing Management" },
          { title: "ChatGPT" },
          { title: "Psychology" },
          { title: "Market Research" },
        ],
      },
      {
        title: "Marketing Analytics & Automation",
        subcategories: [
          { title: "Google Analytics" },
          { title: "HubSpot" },
          { title: "Marketing Analytics" },
          { title: "Google Tag Manager" },
          { title: "Data Analysis" },
          { title: "Marketo" },
          { title: "Custom GPTs/GPT Builder" },
          { title: "Google Analytics Individual Qualification (IQ)" },
          { title: "Marketing Automation" },
        ],
      },
      {
        title: "Public Relations",
        subcategories: [
          { title: "Canva" },
          { title: "Communication Skills" },
          { title: "Podcasting" },
          { title: "Media Training" },
          { title: "Storytelling" },
          { title: "Public Speaking" },
          { title: "Business Communication" },
          { title: "Grant Writing" },
        ],
      },
      {
        title: "Paid Advertising",
        subcategories: [
          { title: "Google Ads (Adwords)" },
          { title: "Google Ads Certification" },
          { title: "Facebook Ads" },
          { title: "PPC Advertising" },
          { title: "Retargeting" },
          { title: "YouTube Marketing" },
          { title: "Advertising Strategy" },
          { title: "Copywriting" },
          { title: "Email Marketing" },
        ],
      },
      {
        title: "Video & Mobile Marketing",
        subcategories: [
          { title: "YouTube Marketing" },
          { title: "YouTube Audience Growth" },
          { title: "Video Creation" },
          { title: "PowerPoint" },
          { title: "InVideo" },
          { title: "Generative AI (GenAI)" },
          { title: "Video Marketing" },
          { title: "Video Production" },
          { title: "Video Editing" },
        ],
      },
      {
        title: "Growth Hacking",
        subcategories: [
          { title: "Digital Marketing" },
          { title: "Marketing Strategy" },
          { title: "Passive Income" },
          { title: "App Marketing" },
          { title: "Account-Based Marketing (ABM)" },
          { title: "ChatGPT" },
          { title: "Facebook Ads" },
          { title: "YouTube Audience Growth" },
        ],
      },
      {
        title: "Content Marketing",
        subcategories: [
          { title: "AI Content Generation" },
          { title: "Content Writing" },
          { title: "Copywriting" },
          { title: "Writing" },
          { title: "Blogging" },
          { title: "Content Creation" },
          { title: "Social Media Marketing" },
          { title: "ChatGPT" },
        ],
      },
      {
        title: "Affiliate Marketing",
        subcategories: [
          { title: "ClickBank" },
          { title: "Google Ads (Adwords)" },
          { title: "Amazon Affiliate Marketing" },
          { title: "Marketing Strategy" },
          { title: "Search Engine Optimization (SEO)" },
          { title: "Generative AI (GenAI)" },
          { title: "Pinterest Marketing" },
          { title: "Influencer Marketing" },
        ],
      },
      {
        title: "Product Marketing",
        subcategories: [
          { title: "Amazon Kindle Direct Publishing (KDP)" },
          { title: "SaaS" },
          { title: "Self-Publishing" },
          { title: "Product Management" },
          { title: "Book Marketing" },
          { title: "Generative AI (GenAI)" },
          { title: "Voice-Over" },
          { title: "Marketing Strategy" },
        ],
      },
      {
        title: "Other Marketing",
        subcategories: [
          { title: "Copywriting" },
          { title: "ChatGPT" },
          { title: "Conversion Rate Optimization (CRO)" },
          { title: "Marketing Strategy" },
          { title: "Event Planning" },
          { title: "Digital Marketing" },
          { title: "Research Paper Writing" },
          { title: "Google Tag Manager" },
          { title: "Marketing Psychology" },
        ],
      },
    ],
  },

  {
    title: "Lifestyle",
    subcategories: [
      {
        title: "Arts & Crafts",
        subcategories: [
          { title: "Drawing" },
          { title: "Watercolor Painting" },
          { title: "Acrylic Painting" },
          { title: "Figure Drawing" },
          { title: "Painting" },
          { title: "Sketching" },
          { title: "Candle Making" },
          { title: "Soapmaking" },
          { title: "Oil Painting" },
        ],
      },
      {
        title: "Beauty & Makeup",
        subcategories: [
          { title: "Beauty" },
          { title: "Makeup Artistry" },
          { title: "Skincare" },
          { title: "Nail Artistry" },
          { title: "Perfume" },
          { title: "Hair Styling" },
          { title: "Cosmetics" },
          { title: "Beauty Business" },
          { title: "Face Lift" },
        ],
      },
      {
        title: "Esoteric Practices",
        subcategories: [
          { title: "Reiki" },
          { title: "Energy Healing" },
          { title: "Tarot Reading" },
          { title: "Astrology" },
          { title: "Spiritual Healing" },
          { title: "Hypnotherapy" },
          { title: "Psychic" },
          { title: "Chakra" },
          { title: "Akashic Records" },
        ],
      },
      {
        title: "Food & Beverage",
        subcategories: [
          { title: "Cooking" },
          { title: "Coffee" },
          { title: "Pastry" },
          { title: "Cocktails and Bartending" },
          { title: "Sourdough Bread Baking" },
          { title: "Bread Baking" },
          { title: "Wine Appreciation and Oenology" },
          { title: "Baking" },
          { title: "Cake Baking" },
        ],
      },
      {
        title: "Gaming",
        subcategories: [
          { title: "Chess" },
          { title: "Poker" },
          { title: "eSports" },
          { title: "Open Broadcaster" },
          { title: "Twitch" },
          { title: "Fortnite" },
          { title: "League of Legends" },
          { title: "Character Design" },
        ],
      },
      {
        title: "Home Improvement & Gardening",
        subcategories: [
          { title: "Woodworking and Carpentry" },
          { title: "Electricity" },
          { title: "Home Repair" },
          { title: "Gardening" },
          { title: "Electrical Wiring" },
          { title: "Mushroom Cultivation" },
          { title: "Farming" },
          { title: "Hydroponics" },
          { title: "Organizational Skills" },
        ],
      },
      {
        title: "Pet Care & Training",
        subcategories: [
          { title: "Dog Training" },
          { title: "Dog Care" },
          { title: "Horsemanship" },
          { title: "Dog Behavior" },
          { title: "Pet Training" },
          { title: "Pet Care" },
          { title: "Animal Nutrition" },
          { title: "Veterinary Medicine" },
          { title: "Cat Behavior" },
        ],
      },
      {
        title: "Travel",
        subcategories: [
          { title: "Travel Tips" },
          { title: "Travel Writing" },
          { title: "Travel Business" },
          { title: "Airbnb Hosting" },
          { title: "Portuguese Language" },
          { title: "Digital Nomad" },
          { title: "Immigration" },
          { title: "Working Abroad" },
        ],
      },
      {
        title: "Other Lifestyle",
        subcategories: [
          { title: "Electronics" },
          { title: "PCB Design" },
          { title: "Drawing" },
          { title: "Stable Diffusion" },
          { title: "Geometric Dimensioning and Tolerancing (GD&T)" },
          { title: "AutoCAD" },
          { title: "CATIA" },
          { title: "Microservices" },
          { title: "Software Architecture" },
        ],
      },
    ],
  },

  {
    title: "Photography & Video",
    subcategories: [
      {
        title: "Digital Photography",
        subcategories: [
          { title: "iPhone Photography" },
          { title: "Photography" },
          { title: "Digital Camera Functionality" },
          { title: "Affinity Photo" },
          { title: "Mobile Photography" },
          { title: "Adobe Lightroom" },
          { title: "GIMP" },
          { title: "Adobe Photoshop" },
        ],
      },
      {
        title: "Photography",
        subcategories: [
          { title: "Photography Composition" },
          { title: "Mobile Photography" },
          { title: "Product Photography" },
          { title: "Digital Photography" },
          { title: "Night Photography" },
          { title: "Landscape Photography" },
          { title: "Street Photography" },
          { title: "Food Photography" },
        ],
      },
      {
        title: "Portrait Photography",
        subcategories: [
          { title: "Photography Lighting" },
          { title: "Posing" },
          { title: "Photography" },
          { title: "Photoshop Retouching" },
          { title: "Family Portrait Photography" },
          { title: "Image Editing" },
          { title: "Video Editing" },
          { title: "Photography Business" },
        ],
      },
      {
        title: "Photography Tools",
        subcategories: [
          { title: "Adobe Lightroom" },
          { title: "Adobe Photoshop" },
          { title: "Image Editing" },
          { title: "Digital Camera Functionality" },
          { title: "Affinity Photo" },
          { title: "Photoshop Retouching" },
          { title: "Drone and Aerial Photography" },
          { title: "Photography" },
          { title: "GIMP" },
        ],
      },
      {
        title: "Commercial Photography",
        subcategories: [
          { title: "Real Estate Photography" },
          { title: "Architecture Photography" },
          { title: "Photography Business" },
          { title: "Photoshop Retouching" },
          { title: "Wedding Photography" },
          { title: "Product Photography" },
          { title: "Photography" },
          { title: "Food Photography" },
          { title: "Drone and Aerial Photography" },
        ],
      },
      {
        title: "Video Design",
        subcategories: [
          { title: "Video Editing" },
          { title: "Adobe Premiere Pro" },
          { title: "Video Production" },
          { title: "DaVinci Resolve" },
          { title: "Adobe After Effects" },
          { title: "CapCut" },
          { title: "Unreal Engine" },
          { title: "Color Grading" },
          { title: "Filmmaking" },
        ],
      },
      {
        title: "Other Photography & Video",
        subcategories: [
          { title: "Generative AI (GenAI)" },
          { title: "YouTube Audience Growth" },
          { title: "iPhone Photography" },
          { title: "Photography" },
          { title: "AI Content Generation" },
          { title: "Drone and Aerial Photography" },
          { title: "Video Editing" },
          { title: "Video Creation" },
          { title: "Filmmaking" },
        ],
      },
    ],
  },

  {
    title: "Health & Fitness",
    subcategories: [
      {
        title: "Fitness",
        subcategories: [
          { title: "Pilates" },
          { title: "Teacher Training" },
          { title: "Personal Trainer Business" },
          { title: "Home Workout" },
          { title: "Muscle Building" },
          { title: "Strength Training" },
          { title: "Stretching Exercise" },
          { title: "Boxing" },
        ],
      },
      {
        title: "General Health",
        subcategories: [
          { title: "Massage" },
          { title: "Herbalism" },
          { title: "Facial Massage" },
          { title: "Breathing Techniques" },
          { title: "Reflexology" },
          { title: "Natural Medicine" },
          { title: "Aromatherapy" },
          { title: "Health" },
          { title: "Holistic Medicine" },
        ],
      },
      {
        title: "Sports",
        subcategories: [
          { title: "Soccer" },
          { title: "Sport Psychology" },
          { title: "Swimming" },
          { title: "Tennis" },
          { title: "Sports Coaching" },
          { title: "Golf" },
          { title: "Sports Massage" },
          { title: "Sports Management" },
          { title: "Running" },
        ],
      },
      {
        title: "Nutrition & Diet",
        subcategories: [
          { title: "Nutrition" },
          { title: "Dieting" },
          { title: "Health Coach Training" },
          { title: "Weight Loss" },
          { title: "Gut Health" },
          { title: "Sports Nutrition" },
          { title: "Vegan Cooking" },
          { title: "Ketogenic Diet" },
          { title: "Face Yoga" },
        ],
      },
      {
        title: "Yoga",
        subcategories: [
          { title: "Pranayama" },
          { title: "Chair Yoga" },
          { title: "Breathing Techniques" },
          { title: "Yoga for Kids" },
          { title: "Ayurveda" },
          { title: "Prenatal Yoga" },
          { title: "Face Yoga" },
          { title: "Tantra" },
        ],
      },
      {
        title: "Mental Health",
        subcategories: [
          { title: "Cognitive Behavioral Therapy (CBT)" },
          { title: "Somatic Therapy" },
          { title: "Psychotherapy" },
          { title: "Art Therapy" },
          { title: "Acceptance and Commitment Therapy (ACT)" },
          { title: "Trauma-Informed Care" },
          { title: "Dialectical Behavior Therapy (DBT)" },
          { title: "Psychology" },
        ],
      },
      {
        title: "Martial Arts & Self Defense",
        subcategories: [
          { title: "Martial Arts" },
          { title: "Self-Defense" },
          { title: "Krav Maga" },
          { title: "Tai Chi" },
          { title: "Brazilian Jiu-Jitsu" },
          { title: "Boxing" },
          { title: "Close Combat" },
          { title: "Wing Chun" },
          { title: "Karate" },
        ],
      },
      {
        title: "Safety & First Aid",
        subcategories: [
          { title: "First Aid" },
          { title: "Workplace Health and Safety" },
          { title: "OSHA" },
          { title: "Herbalism" },
          { title: "Public Health" },
          { title: "Survival Skills" },
          { title: "Fire Safety" },
          { title: "Advanced Trauma Life Support (ATLS)" },
          { title: "Dog Care" },
        ],
      },
      {
        title: "Dance",
        subcategories: [
          { title: "Salsa Dancing" },
          { title: "Belly Dancing" },
          { title: "Bachata" },
          { title: "Hip Hop Dancing" },
          { title: "Ballet" },
          { title: "Tango Dance" },
          { title: "Poi Spinning" },
        ],
      },
      {
        title: "Meditation",
        subcategories: [
          { title: "Mindfulness" },
          { title: "Sound Therapy" },
          { title: "Counseling" },
          { title: "Reiki" },
          { title: "Breathing Techniques" },
          { title: "Qigong" },
          { title: "Mental Health" },
        ],
      },
      {
        title: "Other Health & Fitness",
        subcategories: [
          { title: "Massage" },
          { title: "Sports Massage" },
          { title: "Facial Massage" },
          { title: "Qigong" },
          { title: "Medical Coding" },
          { title: "Spiritual Healing" },
          { title: "Medical Terminology" },
          { title: "Beauty" },
          { title: "Kinesiology Taping" },
        ],
      },
    ],
  },

  {
    title: "Music",
    subcategories: [
      {
        title: "Instruments",
        subcategories: [
          { title: "Guitar" },
          { title: "Piano" },
          { title: "Keyboard Instrument" },
          { title: "Bass Guitar" },
          { title: "Drums" },
          { title: "Piano Chords" },
          { title: "Violin" },
          { title: "Ukulele" },
          { title: "Harmonica" },
        ],
      },
      {
        title: "Music Production",
        subcategories: [
          { title: "Ableton Live" },
          { title: "FL Studio" },
          { title: "Logic Pro" },
          { title: "Music Mixing" },
          { title: "Audio Engineering" },
          { title: "Music Composition" },
          { title: "Sound Design" },
          { title: "Audio Production" },
        ],
      },
      {
        title: "Music Fundamentals",
        subcategories: [
          { title: "Music Theory" },
          { title: "Music Composition" },
          { title: "Songwriting" },
          { title: "Electronic Music" },
          { title: "Reading Music" },
          { title: "Ear Training" },
          { title: "Piano" },
          { title: "Harmony (music)" },
          { title: "Piano Chords" },
        ],
      },
      {
        title: "Vocal",
        subcategories: [
          { title: "Singing" },
          { title: "Voice Training" },
          { title: "Voice Acting" },
          { title: "Meditation" },
          { title: "Raga Music" },
          { title: "Rapping" },
          { title: "Yoga" },
          { title: "Breathing Techniques" },
          { title: "Voice-Over" },
        ],
      },
      {
        title: "Music Techniques",
        subcategories: [
          { title: "DJ" },
          { title: "Reading Music" },
          { title: "Music Composition" },
          { title: "Fingerstyle Guitar" },
          { title: "Piano" },
          { title: "Music Theory" },
          { title: "Guitar" },
          { title: "Music Improvisation" },
          { title: "Piano Chords" },
        ],
      },
      {
        title: "Music Software",
        subcategories: [
          { title: "FL Studio" },
          { title: "Logic Pro" },
          { title: "Music Theory" },
          { title: "Ableton Live" },
          { title: "Music Production" },
          { title: "GarageBand" },
          { title: "DJ" },
          { title: "Sound Design" },
          { title: "Cubase" },
        ],
      },
      {
        title: "Other Music",
        subcategories: [
          { title: "DJ" },
          { title: "Music Business" },
          { title: "Songwriting" },
          { title: "Sound Therapy" },
          { title: "Music Marketing" },
          { title: "Rapping" },
          { title: "Luthiery" },
          { title: "Music Mixing" },
          { title: "Acoustics" },
        ],
      },
    ],
  },

  {
    title: "Teaching & Academics",
    subcategories: [
      {
        title: "Engineering",
        subcategories: [
          { title: "Electrical Engineering" },
          { title: "Mechanical Engineering" },
          { title: "Electricity" },
          { title: "Civil Engineering" },
          { title: "Electronics" },
          { title: "Solar Energy" },
          { title: "Automotive Engineering" },
          { title: "Power Engineering" },
          { title: "Electrical Design" },
        ],
      },
      {
        title: "Humanities",
        subcategories: [
          { title: "Philosophy" },
          { title: "Art History" },
          { title: "Statistics" },
          { title: "World History" },
          { title: "Christianity" },
          { title: "Critical Thinking" },
          { title: "Creative Writing" },
          { title: "Cognitive Behavioral Therapy (CBT)" },
          { title: "Autism" },
        ],
      },
      {
        title: "Math",
        subcategories: [
          { title: "Calculus" },
          { title: "Statistics" },
          { title: "Linear Algebra" },
          { title: "Algebra" },
          { title: "Probability" },
          { title: "Trigonometry" },
          { title: "Geometry" },
          { title: "Discrete Math" },
        ],
      },
      {
        title: "Science",
        subcategories: [
          { title: "Physics Anatomy" },
          { title: "Medical Coding" },
          { title: "Chemistry" },
          { title: "General Chemistry" },
          { title: "Biology" },
          { title: "Quantum Mechanics (physics)" },
          { title: "Certified Professional Coder (CPC)" },
          { title: "Organic Chemistry" },
        ],
      },
      {
        title: "Online Education",
        subcategories: [
          { title: "Online Course Creation" },
          { title: "Instructional Design" },
          { title: "Teaching Online" },
          { title: "Project Management" },
          { title: "Canva" },
          { title: "Moodle" },
          { title: "Coding For Kids" },
          { title: "ChatGPT" },
          { title: "Passive Income" },
        ],
      },
      {
        title: "Social Science",
        subcategories: [
          { title: "Psychology" },
          { title: "Macroeconomics" },
          { title: "Counseling" },
          { title: "Econometrics" },
          { title: "Economics" },
          { title: "Criminology" },
          { title: "Psychotherapy" },
          { title: "Intelligence Analysis (security)" },
          { title: "Cognitive Behavioral Therapy (CBT)" },
        ],
      },
      {
        title: "Language Learning",
        subcategories: [
          { title: "English Language" },
          { title: "German Language" },
          { title: "Spanish Language" },
          { title: "English Grammar" },
          { title: "French Language" },
          { title: "Japanese Language" },
          { title: "English Conversation" },
          { title: "English Vocabulary" },
          { title: "Arabic Language" },
        ],
      },
      {
        title: "Teacher Training",
        subcategories: [
          { title: "Train the Trainer" },
          { title: "Early Childhood Education" },
          { title: "English Language" },
          { title: "Classroom Management" },
          { title: "Instructional Design" },
          { title: "Generative AI (GenAI)" },
          { title: "Voice-Over" },
          { title: "Coaching" },
        ],
      },
      {
        title: "Test Prep",
        subcategories: [
          { title: "IELTS" },
          { title: "TOEFL" },
          { title: "PMI Project Management Professional (PMP)" },
          { title: "Statistics" },
          { title: "Test Taking Skills" },
          {
            title: "Canadian English Language Proficiency Index Program (CELPIP)",
          },
          { title: "PMI PMBOK" },
          { title: "English Language" },
          { title: "CCAT" },
        ],
      },
      {
        title: "Other Teaching & Academics",
        subcategories: [
          { title: "Research Methods" },
          { title: "Medical Coding" },
          { title: "Proofreading" },
          { title: "Medical Billing" },
          { title: "Research Paper Writing" },
          { title: "Academic Writing" },
          { title: "Sewing" },
          { title: "Chess" },
          { title: "Clinical Research" },
        ],
      },
    ],
  },
];
