export const topics = [
  { code: "js", name: "JavaScript", count: 237 },
  { code: "react", name: "React JS", count: 194 },
  { code: "web-dev", name: "Web Development", count: 119 },
  { code: "laravel", name: "Laravel", count: 109 },
  { code: "css", name: "CSS", count: 98 },
  { code: "django", name: "Django", count: 95 },
  { code: "html", name: "HTML", count: 80 },
  { code: "angular", name: "Angular", count: 76 },
  { code: "nodejs", name: "Node.Js", count: 74 },
  { code: "nextjs", name: "Next.js", count: 61 },
  { code: "fullstack", name: "Full Stack Web Development", count: 55 },
  { code: "typescript", name: "Typescript", count: 47 },
  { code: "frontend", name: "Front End Web Development", count: 43 },
  { code: "mern", name: "MERN Stack", count: 43 },
  { code: "flutter", name: "Google Flutter", count: 41 },
  { code: "vuejs", name: "Vue JS", count: 39 },
  { code: "react-native", name: "React Native", count: 38 },
  { code: "python", name: "Python", count: 35 },
  { code: "bootstrap", name: "Bootstrap", count: 31 },
  { code: "php", name: "PHP (programming language)", count: 30 },
];
