const algoSearch = [
  "JavaScript",
  "HTML",
  "CSS",
  "React",
  "Node.js",
  "Django",
  "PHP",
  "Ruby on Rails",
  "Python",
  "R",
  "SQL",
  "Machine Learning",
  "Deep Learning",
  "Data Visualization",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "Android Development",
  "iOS Development",
  "Business Strategy",
  "Leadership",
  "Startups",
  "Freelancing",
  "Unity",
  "Unreal Engine",
  "C#",
  "Game Design",
  "Software Testing",
  "DevOps",
  "APIs",
  "Git",
  "Agile",
  "Scrum",
  "PMP",
  "Risk Management",
  "Kanban",
  "Stock Trading",
  "Cryptocurrency",
  "Options",
  "Forex Trading",
];

module.exports = algoSearch;
