const courseNames: string[] = [
  "Python Programming for Everyone",
  "JavaScript Essentials for Beginners",
  "Full-Stack Web Apps with MERN",
  "React and Redux Advanced Guide",
  "SEO Mastery for Small Businesses",
  "Cybersecurity Basics for Everyone",
  "Java Development Fundamentals",
  "Machine Learning for Absolute Beginners",
  "Data Science with Python and Pandas",
  "Excel Masterclass for Professionals",
  "iOS Development with Swift",
  "Kotlin Programming for Beginners",
  "Flutter App Development Bootcamp",
  "Photoshop for Digital Creatives",
  "The Digital Marketing Blueprint",
  "Startup Success Strategies",
  "Accounting and Bookkeeping Essentials",
  "Stock Market Investing for Beginners",
  "Penetration Testing for Beginners",
  "AWS Advanced Cloud Practitioner",
  "Complete Guide to DevOps Tools",
  "Premiere Pro for Video Creators",
  "Learn Guitar in 30 Days",
  "Public Speaking Made Easy",
  "Scrum and Agile Fundamentals",
  "Effective Business Negotiation Tactics",
  "YouTube Monetization Secrets",
  "Blender 3D Animation Bootcamp",
  "Master Adobe XD from Scratch",
  "Photography Skills for Beginners",
  "Web Scraping with Python Made Simple",
  "Learn Django for Web Applications",
  "Game Development with Unity 3D",
  "Cryptocurrency and Blockchain Masterclass",
  "Introduction to Microsoft Power BI",
  "Mastering Tableau for Data Professionals",
  "Advanced JavaScript Coding Techniques",
  "Kubernetes Masterclass for Developers",
  "Docker for Absolute Beginners",
  "Azure Cloud Solutions Essentials",
  "Launch Your Shopify Store Today",
  "The Ultimate Canva Design Bootcamp",
  "Figma Design for Beginners",
  "SQL for Business Analysts",
  "Yoga for Stress Relief and Relaxation",
  "Master Budgeting for Financial Success",
  "Habits for High Productivity",
  "Quick and Easy Cooking Basics",
  "Knitting Projects for Beginners",
  "Stress Management through Meditation",
  "Freelancing on Fiverr",
  "Effective Team Management Skills",
  "Write Stories That Sell",
  "Creative Writing for Aspiring Authors",
  "Unreal Engine: Create Virtual Worlds",
  "Graphic Design 101: Beginners’ Guide",
  "Building Advanced HTML & CSS Websites",
  "Python APIs for Web Development",
  "Social Media Growth Strategies",
  "Illustrator Techniques for Designers",
  "Time Management for Entrepreneurs",
  "Solve Problems with Design Thinking",
  "Beginner’s Guide to Stock Trading",
  "Complete PMP Exam Preparation",
  "LinkedIn Profile Optimization",
  "Basics of Interior Decorating",
  "Instagram Marketing Strategies",
  "Artificial Intelligence Explained Simply",
  "Freelancing: Build a Winning Profile",
  "Game Programming with C#",
  "QuickBooks for Entrepreneurs",
  "Data Visualization with Excel",
  "Negotiation Skills for Sales Professionals",
  "Storytelling for Content Creators",
  "CSS3 Advanced Techniques",
  "Canva for Marketing Professionals",
  "Power BI Data Reporting Made Easy",
  "Neural Networks with TensorFlow",
  "E-Learning Content Creation Guide",
  "Stage Presence for Public Speaking",
  "Scrum Techniques for Agile Teams",
  "Write SEO-Friendly Content",
  "Productivity Through Mindfulness",
  "Create Apps with React Native",
  "InDesign for Marketing Materials",
  "Ethical Hacking: Learn the Basics",
  "Data Analytics Career Guide",
  "Freelancing: A Step-by-Step Guide",
  "Financial Modeling with Excel",
  "CorelDRAW Advanced Techniques",
  "Digital Drawing for Beginners",
  "Raspberry Pi: Fun DIY Projects",
  "Affiliate Marketing Step-by-Step",
  "Amazon Seller Success Guide",
  "Lightroom Mastery for Photographers",
  "Personal Training Fundamentals",
  "Modern UI Design with Sketch",
  "Game Design Mastery",
  "Video Production and Editing Skills",
  "Mastering AI for Daily Tasks",
  "Mastering Python for Beginners",
  "Advanced JavaScript Techniques",
  "Full-Stack Web Development Bootcamp",
  "React and Redux Essentials",
  "The Complete SEO Guide",
  "Cybersecurity from Scratch",
  "Java Programming Masterclass",
  "Machine Learning with Python",
  "Data Science with R for Beginners",
  "The Ultimate Excel Bootcamp",
  "Swift Programming for iOS Development",
  "Kotlin for Android Development",
  "Flutter for Cross-Platform Apps",
  "Graphic Design Mastery with Photoshop",
  "Digital Marketing 101",
  "Entrepreneurship: Launch Your First Startup",
  "Financial Accounting Basics",
  "Investing and Stock Market Strategies",
  "Ethical Hacking for Beginners",
  "AWS Cloud Practitioner Essentials",
  "DevOps Fundamentals: Tools and Practices",
  "Video Editing with Adobe Premiere Pro",
  "Guitar for Absolute Beginners",
  "Mastering Public Speaking Skills",
  "Agile Project Management Mastery",
  "The Art of Negotiation",
  "Creating a Successful YouTube Channel",
  "3D Modeling with Blender",
  "Prototyping with Adobe XD",
  "Photography Masterclass: DSLR Basics",
  "Python Automation: Web Scraping and More",
  "The Complete Django Developer Course",
  "Unity Game Development Bootcamp",
  "Blockchain and Cryptocurrency Explained",
  "Microsoft Power BI for Beginners",
  "Tableau Data Visualization Mastery",
  "JavaScript: The Advanced Concepts",
  "Kubernetes for Developers",
  "Docker Essentials: Containers Made Easy",
  "Mastering Microsoft Azure",
  "Building Your First Shopify Store",
  "The Complete Canva Design Course",
  "Figma for UI/UX Designers",
  "SQL for Data Analysis and Visualization",
  "Home Yoga Practice for Wellness",
  "Personal Finance: Budgeting and Saving",
  "Mindset Mastery for Success",
  "Cooking Fundamentals for Beginners",
  "Knitting Basics: Make Your First Scarf",
  "Meditation and Stress Management Techniques",
  "Start Freelancing with Upwork",
  "Leadership and Team Building Skills",
  "Writing Compelling Stories for Business",
  "Creative Writing: The Basics",
  "Virtual Reality Development with Unreal Engine",
  "The Beginner’s Guide to Graphic Design",
  "Building Responsive Websites with HTML & CSS",
  "Mastering APIs with Python",
  "Social Media Marketing for Small Businesses",
  "Learn Adobe Illustrator from Scratch",
  "Time Management for Busy Professionals",
  "Design Thinking for Problem Solving",
  "Stock Trading Strategies for Beginners",
  "PMP Certification Exam Prep",
  "Personal Branding with LinkedIn",
  "Interior Design Basics: Space Planning",
  "Content Creation for Instagram Growth",
  "Introduction to Artificial Intelligence",
  "Freelancing: Create a Winning Portfolio",
  "C# for Game Development",
  "QuickBooks for Small Businesses",
  "Data Visualization with Google Sheets",
  "Negotiation Tactics for Everyday Life",
  "Storytelling for Brand Building",
  "Advanced CSS Animations and Transitions",
  "The Complete Canva Marketing Course",
  "Power BI Dashboards from Scratch",
  "Deep Learning with TensorFlow",
  "Creating Engaging E-Learning Content",
  "Public Speaking: Overcome Stage Fright",
  "Fundamentals of Agile and Scrum",
  "SEO Content Writing Techniques",
  "Meditation for Productivity",
  "Building Mobile Apps with React Native",
  "Adobe InDesign for Print Designers",
  "Ethical Hacking: Network Security Basics",
  "Building a Career in Data Analytics",
  "The Complete Freelancing Masterclass",
  "Excel for Financial Modeling",
  "CorelDRAW for Graphic Design",
  "Digital Art with Procreate",
  "Raspberry Pi Projects for Beginners",
  "Affiliate Marketing Basics",
  "Amazon FBA for Beginners",
  "Photography Editing with Lightroom",
  "Personal Training Certification Prep",
  "Sketch for Modern UI Design",
  "Game Design Fundamentals",
  "Creative Video Editing Techniques",
  "Introduction to ChatGPT for Productivity",
  "Python Fundamentals for Beginners",
  "JavaScript Basics to Advanced",
  "Full-Stack Development with Vue.js",
  "Master React in 30 Days",
  "Advanced SEO Strategies",
  "Introduction to Cybersecurity Tools",
  "Learn Java Programming from Scratch",
  "Machine Learning with Scikit-Learn",
  "Data Science for Business Analytics",
  "Excel for Financial Professionals",
  "Build iOS Apps with SwiftUI",
  "Kotlin Essentials for App Development",
  "Cross-Platform Apps with Flutter",
  "Photoshop for Beginners to Experts",
  "Digital Marketing: The Complete Guide",
  "Entrepreneurship Bootcamp for Creatives",
  "Accounting Made Easy for Entrepreneurs",
  "Stock Market Basics for Beginners",
  "Advanced Ethical Hacking Techniques",
  "AWS Solutions Architect Associate Prep",
  "DevOps for Software Engineers",
  "Video Editing for Social Media",
  "Guitar Lessons for Busy Professionals",
  "Public Speaking for Professionals",
  "Scrum and Agile Project Management",
  "Master Negotiation in Business",
  "Start Your Own YouTube Channel",
  "Blender for 3D Artists",
  "Adobe XD: Prototyping and Design",
  "Photography Techniques for Beginners",
  "Advanced Python for Automation",
  "Learn Django with Real Projects",
  "Unity for Game Programming",
  "Blockchain Technology Explained",
  "Data Visualization with Python",
  "Tableau for Advanced Data Analytics",
  "JavaScript Frameworks: Angular and React",
  "Introduction to Kubernetes Clusters",
  "Docker Mastery for Developers",
  "Azure Fundamentals for Beginners",
  "Building an Online Shopify Store",
  "Canva for Social Media Managers",
  "Figma Design Essentials",
  "SQL Queries for Beginners",
  "Yoga for Physical and Mental Health",
  "Personal Budgeting Made Simple",
  "Master Productivity with Proven Techniques",
  "Learn Cooking from Scratch",
  "Knitting: Beyond Basics",
  "Meditation for a Balanced Life",
  "Freelancing Basics: How to Get Started",
  "Building Leadership Qualities",
  "Master Creative Storytelling",
  "Writing Skills for Professional Success",
  "Unreal Engine Basics for Game Design",
  "Graphic Design for Entrepreneurs",
  "Learn HTML and CSS in a Week",
  "Python for Backend Development",
  "Social Media Marketing Techniques",
  "Illustrator for Creative Professionals",
  "Time Management for High Performers",
  "Design Thinking for Teams",
  "Investing in Stocks: A Beginner's Guide",
  "PMP Certification Crash Course",
  "LinkedIn Marketing for Job Seekers",
  "Decorating Your Space Like a Pro",
  "Instagram Ads for Beginners",
  "AI Tools for Everyday Use",
  "Freelancing: Build Your First Gig",
  "Unity Game Programming Mastery",
  "QuickBooks for Small Business Owners",
  "Microsoft Excel Advanced Features",
  "Sales Skills: Closing Deals with Confidence",
  "Content Creation: Telling Your Brand Story",
  "CSS Tricks and Responsive Design",
  "Canva Design for Branding",
  "Power BI Reports Made Simple",
  "Neural Networks and AI Fundamentals",
  "E-Learning Tools for Teachers",
  "Presenting with Confidence and Clarity",
  "Scrum Methodologies for Teams",
  "SEO Writing Techniques for Content Creators",
  "Mindfulness Practices for a Productive Life",
  "Building React Native Apps for iOS and Android",
  "InDesign for Digital Publishing",
  "Learn Ethical Hacking Step-by-Step",
  "Data Analytics for Non-Programmers",
  "Freelancing on Upwork Made Easy",
  "Financial Modeling with Spreadsheets",
  "Advanced Techniques in CorelDRAW",
  "Digital Illustration for Storytelling",
  "Raspberry Pi for IoT Projects",
  "Affiliate Marketing: Start Earning Today",
  "Amazon Affiliate Marketing Guide",
  "Photo Editing with Adobe Lightroom",
  "Personal Trainer Certification Study Guide",
  "UI/UX Design with Sketch and Figma",
  "Game Storyboarding and Concept Design",
  "Mastering Premiere Pro for Filmmakers",
  "AI Tools for Productivity",
  "Build Modern Web Apps with Angular",
  "Microsoft Azure for Cloud Computing",
  "E-Commerce Website Development with WooCommerce",
  "Master Blender for 3D Game Assets",
  "Introduction to Penetration Testing",
  "Comprehensive Guide to Personal Branding",
  "Facebook Ads for Beginners",
  "Master Time and Stress Management",
  "Python Scripting for IT Professionals",
  "The Ultimate React Developer's Guide",
  "Learn 3D Animation with Maya",
  "Starting a Podcast: A Beginner's Guide",
  "The Complete Marketing Funnel Mastery",
  "Resume Writing for Career Success",
  "How to Build a Passive Income Business",
  "LinkedIn Advertising for Businesses",
  "Customer Service Mastery",
  "Negotiation Skills for Business Deals",
  "Basics of Agile Development",
  "Create Digital Art with Procreate",
  "Advanced Financial Accounting Techniques",
  "Learn C++ for Software Development",
  "Introduction to Data Warehousing",
  "Build Interactive Dashboards with Tableau",
  "AWS DevOps Engineer Certification Prep",
  "Cybersecurity for IT Professionals",
  "Content Strategy for Marketing Success",
  "Google Analytics for Website Insights",
  "Developing a Growth Mindset",
  "YouTube Video Production for Beginners",
  "Brand Identity Design with Canva",
  "Figma Advanced Prototyping Techniques",
  "Learn SQL for Data Science",
  "Writing Copy That Converts",
  "Photography Business Basics",
  "Mastering Email Marketing",
  "Developing IoT Applications with Arduino",
  "Investing in Real Estate for Beginners",
  "Music Production with FL Studio",
  "Learn the Basics of Freelancing",
  "Master JavaScript for Modern Web Development",
  "Cryptocurrency Wallets and Transactions",
  "Mobile App Marketing for Developers",
  "Mastering the Basics of Agile",
  "Learn Deep Learning with PyTorch",
  "Building Engaging Social Media Campaigns",
  "Introduction to Augmented Reality",
  "Financial Accounting for Beginners",
  "Master the Art of Storyboarding",
  "Learn Responsive Web Design",
  "Intro to Cloud Computing with Google Cloud",
  "Learn Unity for 2D Game Development",
  "Basics of Technical Writing",
  "Design Mobile-First Websites",
  "Learn Ethical Hacking with Kali Linux",
  "Start Your Photography Business Today",
  "Digital Marketing Campaigns That Work",
  "Master the Principles of Animation",
  "Sales Funnels for Online Businesses",
  "Develop Advanced Excel Skills",
  "Learn Branding with Case Studies",
  "Basics of AI and Machine Learning",
  "Create Professional E-Learning Courses",
  "How to Manage Remote Teams Effectively",
  "Learn Color Grading in Premiere Pro",
  "Introduction to Python for Finance",
  "Kubernetes for Cloud-Native Development",
  "Mastering Git and Version Control",
  "Excel Pivot Tables and Charts Mastery",
  "QuickBooks Online Advanced Guide",
  "Affiliate Marketing: Monetize Your Blog",
  "Learn Tableau for Data Visualization",
  "WordPress Website Development Mastery",
  "Mastering Adobe Illustrator Effects",
  "Python Crash Course for Beginners",
  "Advanced JavaScript ES6+",
  "React Hooks and Context API Masterclass",
  "SEO Secrets for Business Growth",
  "Cybersecurity for Small Businesses",
  "Java Fundamentals for Developers",
  "Deep Learning with PyTorch",
  "Data Science Projects with Python",
  "Excel for Financial Analysis",
  "Building iOS Apps with SwiftUI",
  "Android App Development with Kotlin",
  "Learn Flutter for Beginners",
  "Photoshop Retouching Mastery",
  "The Complete Digital Marketing Plan",
  "Startup Guide for Entrepreneurs",
  "Bookkeeping Basics for Small Business",
  "Stock Market Investing Fundamentals",
  "Become an Ethical Hacker",
  "AWS Certified Developer Prep",
  "DevOps Tools: Jenkins, Ansible, Docker",
  "Premiere Pro for Social Media Content",
  "Learn Guitar Chords and Strumming",
  "Public Speaking for Corporate Success",
  "Scrum Fundamentals for Agile Teams",
  "Negotiation Masterclass: Win Every Deal",
  "How to Start and Monetize a Blog",
  "3D Modeling for Beginners with Blender",
  "Design Interactive Prototypes in Adobe XD",
  "DSLR Photography for Beginners",
  "Web Scraping Techniques with Python",
  "Build Real-World Apps with Django",
  "Unity C# for Game Developers",
  "Cryptocurrency Explained for Everyone",
  "Data Visualization with Power BI",
  "Master Tableau for Business Intelligence",
  "Modern JavaScript Best Practices",
  "Kubernetes for System Administrators",
  "Advanced Docker for Microservices",
  "Azure AI Solutions for Developers",
  "Launch a Shopify Store Step by Step",
  "Canva for Content Creators",
  "Design UI Projects with Figma",
  "SQL Mastery for Data Analysis",
  "Yoga for Beginners: Stress Relief",
  "Master Budget Planning Techniques",
  "Boost Your Productivity with Habits",
  "Home Cooking: Delicious Recipes Simplified",
  "Knitting Techniques for Patterns",
  "Advanced Meditation Practices",
  "Freelancing 101: Build a Career Online",
  "Leadership Skills for New Managers",
  "Master Storytelling for Personal Branding",
  "Professional Writing for Business",
  "Game Design with Unreal Engine",
  "Learn Graphic Design Essentials",
  "HTML5 and CSS3: Create Stunning Websites",
  "Python for Data Automation",
  "Social Media Growth Hacks",
  "Illustrator for Logo Design",
  "Time Management for Busy Parents",
  "Creative Problem Solving Techniques",
  "Investing for Passive Income",
  "The Complete PMP Certification Course",
  "LinkedIn for Networking and Career Growth",
  "Interior Design on a Budget",
  "Instagram Marketing Strategies for Brands",
  "AI for Small Businesses",
  "Freelancing on Freelancer.com",
  "Advanced Game Programming with Unity",
  "QuickBooks Essentials for Accountants",
  "Excel for Advanced Data Modeling",
  "Mastering Sales Techniques",
  "Content Creation for Digital Marketing",
  "Advanced CSS Grid and Flexbox Layouts",
  "Canva Mastery for Branding and Marketing",
  "Power BI for Data Storytelling",
  "Neural Network Applications with TensorFlow",
  "Creating Engaging E-Learning Modules",
  "Presentation Skills for Professionals",
  "The Agile Scrum Master Certification",
  "SEO Writing for Blogs and Websites",
  "Mindfulness for a Focused Life",
  "Cross-Platform Mobile Apps with React Native",
  "InDesign for Professional Documents",
  "Become a Certified Ethical Hacker",
  "Data Analytics with Python and Pandas",
  "Freelancing for Tech Professionals",
  "Learn Advanced Financial Modeling",
  "CorelDRAW Essentials for Designers",
  "Digital Painting with Procreate",
  "Raspberry Pi Projects for Smart Homes",
  "Affiliate Marketing for Beginners",
  "How to Succeed with Amazon Affiliate",
  "Lightroom for Advanced Photo Editing",
  "Fitness Coaching Certification Guide",
  "UI/UX Design Tools and Techniques",
  "Game Storytelling and Writing",
  "Adobe Premiere Pro for Beginners",
  "Master AI for Everyday Life",
  "Learn Angular for Modern Web Apps",
  "Google Cloud Basics for Beginners",
  "Build E-Commerce Sites with WooCommerce",
  "Master 3D Texturing in Blender",
  "Penetration Testing for Security Professionals",
  "Create a Personal Brand That Sells",
  "Learn Facebook Marketing for Ads",
  "Stress Management for Professionals",
  "Python Web Development with Flask",
  "React Development from Basics to Advanced",
  "Animation with Blender for Games",
  "Podcasting: Launch Your Show Today",
  "Advanced Marketing Funnel Strategies",
  "Craft the Perfect Resume",
  "Build a Successful Side Hustle",
  "LinkedIn Advertising for Beginners",
  "Customer Relationship Management Skills",
  "Negotiation for Freelancers and Creators",
  "Agile Development for Modern Teams",
  "Digital Art Mastery with Tablets",
  "Accounting for Non-Accountants",
  "Learn Object-Oriented Programming in C++",
  "Data Engineering Fundamentals",
  "Build Stunning Dashboards with Tableau",
  "AWS DevOps Mastery Course",
  "Cybersecurity Strategies for Professionals",
  "Content Strategy for Social Media Success",
  "Google Analytics for Beginners",
  "Cultivating a Growth Mindset for Success",
  "YouTube Growth Strategies for 2023",
  "Branding Basics with Canva Templates",
  "Figma for Web Designers",
  "SQL for Everyday Business Use",
  "Learn to Write High-Performing Copy",
  "How to Start Your Photography Business",
  "Master Email Marketing Campaigns",
  "IoT Development with Arduino",
  "Real Estate Investing Mastery",
  "Advanced Music Production in FL Studio",
  "Freelancing on Fiverr Pro",
  "Build Advanced Web Apps with Angular",
  "Cryptocurrency: Wallets and Transactions",
  "Mobile App Growth Hacking Techniques",
  "Deep Learning for AI Developers",
  "Social Media Campaign Management",
  "Learn Augmented Reality Development",
  "Accounting Reports Made Easy",
  "Storyboard Creation for Game Designers",
  "Responsive Web Design: Beyond Basics",
  "Cloud Computing with AWS Solutions",
  "Learn Unity 2D Game Development",
  "Introduction to API Integration",
  "Master CSS Animation Techniques",
  "Become an Expert in SQL Databases",
  "Lightroom for Mobile Editing",
  "Podcast Marketing Strategies",
  "Basics of Financial Risk Management",
  "Mastering ChatGPT for Content Writing",
  "React Native for Mobile Apps",
  "Start Your Coaching Business Online",
  "Learn AWS for Big Data",
  "Pandas Data Analysis for Beginners",
  "Cybersecurity Management for IT Teams",
  "Master Procreate for Digital Art",
  "Freelancing Contracts and Negotiations",
  "Advanced Web Development with Vue.js",
  "Learn Git and Version Control",
  "Time-Saving Excel Tips and Tricks",
  "Amazon KDP Publishing Masterclass",
  "Web Design with Adobe XD",
  "3D Game Assets with Blender",
  "Becoming a Software Tester",
  "Adobe Illustrator for Beginners",
  "Penetration Testing Advanced Skills",
  "Launch Your Online Business Today",
  "Learn Marketing Automation Tools",
  "Introduction to Cryptocurrency Trading",
  "Build Interactive Web Apps with React",
  "The Science of Productivity",
  "Learn Blogging for Passive Income",
  "Master Social Media Analytics",
  "Machine Learning with Keras",
  "Build Chatbots with AI Tools",
  "Master Marketing on TikTok",
  "C# Fundamentals for Game Developers",
  "Interior Design Principles Simplified",
  "Complete Guide to Business Strategy",
  "AWS Security Specialization",
  "Video Content Creation for Beginners",
  "Building Secure REST APIs with Flask",
  "Productivity Systems for Busy People",
  "Data Science with R Studio",
  "Learn to Build Shopify Apps",
  "Graphic Design for Marketing Teams",
  "Build Games with Unreal Engine",
];

export default courseNames;
