const lessonsNames = [
  // Python Lessons
  "What is Python and Why Use It?",
  "Installing Python and Setting Up the IDE",
  "Understanding Python Syntax and Indentation",
  "Writing Your First Python Program",
  "Exploring Data Types in Python",
  "Using Conditional Statements",
  "Understanding Loops in Python",
  "Defining and Using Functions",
  "Working with Python Libraries",
  "Debugging Python Code",

  // JavaScript Lessons
  "Introduction to JavaScript",
  "How to Include JavaScript in HTML",
  "Understanding Variables: var, let, and const",
  "Writing Functions in JavaScript",
  "Introduction to JavaScript Events",
  "Manipulating the DOM",
  "Using JavaScript Arrays and Methods",
  "Understanding Objects in JavaScript",
  "JavaScript Promises and Async/Await",
  "Common JavaScript Errors and Debugging",

  // React Lessons
  "Setting Up a React Development Environment",
  "Understanding React Components",
  "Working with Props in React",
  "Managing State in React Components",
  "Using React Lifecycle Methods",
  "Introduction to React Hooks",
  "Building Reusable Components",
  "React Router for Navigation",
  "Handling Forms in React",
  "Deploying a React Application",

  // Digital Marketing Lessons
  "What is Digital Marketing?",
  "Creating a Digital Marketing Strategy",
  "SEO: On-Page and Off-Page Optimization",
  "Keyword Research Tools and Techniques",
  "Understanding Google Ads",
  "Building a Social Media Calendar",
  "Introduction to Email Marketing",
  "Using Analytics to Measure Campaign Success",
  "Content Marketing Best Practices",
  "Affiliate Marketing for Passive Income",

  // Web Development Lessons
  "HTML Basics: Tags and Attributes",
  "Creating a Simple HTML Page",
  "CSS Fundamentals: Selectors and Properties",
  "Introduction to Responsive Design",
  "Working with Flexbox and Grid",
  "Using JavaScript to Add Interactivity",
  "Introduction to Backend Development",
  "Connecting to a Database",
  "Building a Contact Form",
  "Publishing a Website Online",

  // Data Science Lessons
  "What is Data Science?",
  "Introduction to Data Analysis with Pandas",
  "Data Cleaning and Preprocessing",
  "Using Matplotlib for Data Visualization",
  "Understanding NumPy Arrays",
  "Introduction to Machine Learning Algorithms",
  "Exploring Classification and Regression Models",
  "Building a Simple Predictive Model",
  "Evaluating Model Performance",
  "Deploying a Machine Learning Model",

  // Cybersecurity Lessons
  "What is Cybersecurity?",
  "Understanding Threats and Vulnerabilities",
  "Introduction to Firewalls",
  "Basics of Network Security",
  "Using Antivirus Software Effectively",
  "Understanding Social Engineering Attacks",
  "Introduction to Ethical Hacking",
  "Creating Strong Passwords",
  "Encrypting Data for Security",
  "Setting Up Two-Factor Authentication",

  // UI/UX Design Lessons
  "What is UI/UX Design?",
  "Understanding User Personas",
  "Wireframing Basics",
  "Designing for Accessibility",
  "Creating Prototypes with Figma",
  "Choosing Fonts and Typography",
  "Introduction to Color Theory",
  "Designing for Different Screen Sizes",
  "Conducting Usability Testing",
  "Building a Style Guide",

  // Business Lessons
  "How to Identify a Business Opportunity",
  "Conducting Market Research",
  "Creating a Unique Value Proposition",
  "Understanding Business Finances",
  "Basics of Branding",
  "Effective Sales Techniques",
  "Leadership Styles and Their Impact",
  "Building a Team Culture",
  "Writing a Business Plan",
  "Developing a Pitch Deck",

  // Graphic Design Lessons
  "What is Graphic Design?",
  "Basics of Adobe Photoshop",
  "Introduction to Adobe Illustrator",
  "Understanding File Formats",
  "Using Layers in Photoshop",
  "Creating Vector Graphics in Illustrator",
  "Logo Design Best Practices",
  "Choosing the Right Fonts for Design",
  "Editing Photos for Social Media",
  "Designing a Flyer or Poster",

  // Personal Development Lessons
  "Understanding Self-Motivation",
  "How to Set SMART Goals",
  "Building a Morning Routine",
  "Overcoming Negative Thought Patterns",
  "Techniques for Stress Management",
  "The Importance of Emotional Intelligence",
  "How to Build Confidence",
  "Effective Time Management Tips",
  "Developing a Growth Mindset",
  "Practicing Gratitude Daily",

  // Finance Lessons
  "Introduction to Personal Finance",
  "Understanding Income and Expenses",
  "Creating a Monthly Budget",
  "Basics of Credit Scores",
  "How to Save for Emergencies",
  "Introduction to Stock Market Investing",
  "Exploring Different Investment Types",
  "Retirement Planning Basics",
  "Understanding Debt and Repayment",
  "Building Wealth Over Time",

  // Lifestyle Lessons
  "Introduction to Healthy Living",
  "Understanding Balanced Nutrition",
  "Basics of Yoga for Beginners",
  "How to Plan a Budget-Friendly Vacation",
  "Photography Tips for Outdoor Shots",
  "DIY Home Decor Projects",
  "Getting Started with Meditation",
  "Introduction to Cooking Techniques",
  "How to Learn a Musical Instrument",
  "Setting Goals for Personal Hobbies",
];

module.exports = lessonsNames;
