const sectionNames = [
  // Python Programming Sections
  "Introduction to Python Basics",
  "Working with Data Types and Variables",
  "Control Flow: Loops and Conditionals",
  "Functions and Modules in Python",
  "File Handling and Exceptions",
  "Python Object-Oriented Programming",
  "Web Scraping with Python",
  "Automating Tasks with Python Scripts",
  "Introduction to Python Libraries",
  "Project: Build a Python Calculator",

  // JavaScript Sections
  "JavaScript Fundamentals",
  "Understanding Variables and Scope",
  "DOM Manipulation Basics",
  "Event Handling in JavaScript",
  "Working with Arrays and Objects",
  "Async JavaScript: Promises and Async/Await",
  "JavaScript ES6 Features",
  "Project: Interactive Web Page",
  "Debugging and Error Handling",
  "JavaScript Best Practices",

  // React Sections
  "Introduction to React Framework",
  "Understanding JSX and Components",
  "State Management in React",
  "React Lifecycle Methods",
  "Using React Hooks",
  "Routing with React Router",
  "Project: Build a Todo App with React",
  "Context API for Global State Management",
  "React and Redux Integration",
  "Deploying a React App",

  // Digital Marketing Sections
  "Overview of Digital Marketing",
  "SEO Fundamentals",
  "Social Media Marketing Strategies",
  "Email Marketing Essentials",
  "Content Marketing Techniques",
  "Google Ads and PPC Campaigns",
  "Using Analytics to Measure Performance",
  "Affiliate Marketing for Beginners",
  "Building an Effective Marketing Funnel",
  "Marketing Automation Tools",

  // Web Development Sections
  "HTML Basics: Building Blocks of the Web",
  "CSS Fundamentals and Styling",
  "Responsive Design with Media Queries",
  "Introduction to JavaScript for Interactivity",
  "Version Control with Git and GitHub",
  "Working with APIs in Web Development",
  "Introduction to Frontend Frameworks",
  "Project: Build a Portfolio Website",
  "Web Performance Optimization",
  "Hosting and Deploying Websites",

  // Data Science Sections
  "Introduction to Data Science Concepts",
  "Data Analysis with Pandas",
  "Data Visualization with Matplotlib",
  "Working with NumPy for Data Manipulation",
  "Statistical Analysis Basics",
  "Introduction to Machine Learning",
  "Supervised and Unsupervised Learning",
  "Project: Data Cleaning and Analysis",
  "Building Predictive Models",
  "Deploying Machine Learning Models",

  // Cybersecurity Sections
  "Introduction to Cybersecurity",
  "Understanding Threats and Vulnerabilities",
  "Network Security Essentials",
  "Ethical Hacking Fundamentals",
  "Penetration Testing Techniques",
  "Introduction to Cryptography",
  "Best Practices for Data Protection",
  "Secure Coding Guidelines",
  "Incident Response and Recovery",
  "Project: Setting Up a Secure Network",

  // UI/UX Design Sections
  "Understanding the Basics of UI/UX Design",
  "Wireframing and Prototyping Tools",
  "Designing User-Centric Interfaces",
  "Introduction to Figma for UI Design",
  "Usability Testing and Feedback",
  "Responsive Web Design Principles",
  "Creating Style Guides and Design Systems",
  "Building Interactive Prototypes",
  "Accessibility in Design",
  "Project: Design a Mobile App UI",

  // Business and Entrepreneurship Sections
  "Developing a Business Idea",
  "Creating a Winning Business Plan",
  "Understanding Market Research",
  "Financial Planning and Budgeting",
  "Building a Strong Brand Identity",
  "Sales Strategies for Entrepreneurs",
  "Leadership and Team Management",
  "Effective Communication Skills",
  "Time Management for Entrepreneurs",
  "Project: Launch a Startup",

  // Graphic Design Sections
  "Introduction to Graphic Design Principles",
  "Working with Adobe Photoshop",
  "Mastering Illustrator for Vector Graphics",
  "Designing for Print and Digital Media",
  "Typography Basics",
  "Color Theory and Application",
  "Logo Design Fundamentals",
  "Creating Social Media Graphics",
  "Photo Editing and Retouching",
  "Project: Design a Brand Identity",

  // Personal Development Sections
  "Understanding Mindset and Motivation",
  "Setting and Achieving Goals",
  "Building Productive Habits",
  "Time Management Strategies",
  "Improving Communication Skills",
  "Confidence and Self-Esteem Building",
  "Overcoming Procrastination",
  "Developing Emotional Intelligence",
  "Stress Management Techniques",
  "Project: Create a Personal Development Plan",

  // Finance and Accounting Sections
  "Basics of Personal Finance",
  "Understanding Financial Statements",
  "Budgeting and Saving Strategies",
  "Tax Planning for Beginners",
  "Introduction to Investing",
  "Stock Market Basics",
  "Cryptocurrency and Blockchain Overview",
  "Building Wealth Over Time",
  "Managing Debt Effectively",
  "Project: Create a Personal Finance Tracker",

  // Lifestyle Sections
  "Introduction to Healthy Living",
  "Meal Planning and Nutrition Basics",
  "Home Workouts and Fitness Routines",
  "Practicing Mindfulness and Meditation",
  "Hobby Ideas for Relaxation",
  "Travel Planning on a Budget",
  "DIY Projects for Home Improvement",
  "Photography Tips for Beginners",
  "Music Basics: Learn an Instrument",
  "Project: Start a New Hobby",
];

module.exports = sectionNames;
